### ISSUE TITLE
Flipped Normals

### ISSUE THREAD

**Issue by Lilothestitch16** [dtzxporter/io_model_semodel#15]
When I extract models from Resident Evil 7 as semodel and import the .semodel in Blender or Maya, the normals are flipped. What is causing this?
![unknown](https://user-images.githubusercontent.com/8963276/123577315-9d146c80-d7a1-11eb-86cd-efaf8055a2ef.png)

**Comment by dtzxporter** [comment]
The tool needs to change the face order.
