### ISSUE TITLE
Blender can't find it

### ISSUE THREAD

**Issue by Devostated** [dtzxporter/io_model_semodel#2]
Hello,
after installing the addon i can't find it in addons.
Console says Modules installed.
I'm looking for Testing addons aswell.
The addon folder even exists in Blender\2.80\scripts\addons

I updated Blender today, could it be that it's not working with the very latest version?

![Capture](https://user-images.githubusercontent.com/30211694/56183181-b17f4b00-6015-11e9-8479-61b53340250f.PNG)

**Comment by Devostated** [comment]
Fixed it by renaming "io_model_semodel-blender-2.8" to "io_model_semodel"

**Comment by zxelo** [comment]
I can't use the file, I even updated my blender too. I even changed the name like Devostated, but I still can open the file but can see it on blender. Can you please help

**Comment by Devostated** [comment]
Tried this version? https://github.com/dtzxporter/io_model_semodel/tree/blender-2.8

**Comment by zxelo** [comment]
yes

**Comment by zxelo** [comment]
i don't even know what i am looking for when i search in blender search. I did semodle but found nothing

**Comment by Devostated** [comment]
I can find it when I type `sem`
try this https://github.com/Devostated/io_model_semodel/releases/tag/test

**Comment by zxelo** [comment]
im reloading my blender, to see if thats the issue. if it doesn't work you will hear from me again!

**Comment by zxelo** [comment]
didn't work , its fine

**Comment by Devostated** [comment]
check `C:\Users\%username%\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons`  maybe it's already there, but broken


Edit:
Fixed file path

**Comment by zxelo** [comment]
ok i got it working but when i go to my application to open, its just blank

**Comment by Devostated** [comment]
What exactly do you mean with just blank?
