### ISSUE TITLE
Blender 2.8 importer does not work

### ISSUE THREAD

**Issue by Airyzz** [dtzxporter/io_model_semodel#3]
Hi, the blender 2.8 importer does not work. However, I have fixed it [here](https://github.com/Airyzz/io_model_semodel/tree/blender-2_8)

There were 3 problems:

1. the fact that your branch is called `blender-2.8` and contains '.' stops the plugin from being able to be loaded

2. I had to remove `"support": "COMMUNITY"` from bl_info. not sure why...

3. I had to replace `bpy.context.scene.update()` at line 231 as this function no longer exists in blender 2.8, I replaced it with 
```python
    layer = bpy.context.view_layer
    layer.update()
```

I would've made a pull request but since some of the issues involve renaming branched I couldn't really do that, or at least I don't know how to.

**Comment by dtzxporter** [comment]
Fixed on master. (blender-28)
