### ISSUE TITLE
Upgrade to 2.8x required !

### ISSUE THREAD

**Issue by shanjoel** [dtzxporter/io_model_semodel#7]
tried to add the add on,couldn't add the add on to blender 
(Upgrade to 2.8x required) !

**Comment by wiizzl** [comment]
i have the same problem :(

**Comment by kaosity** [comment]
how do i fix this?

**Comment by Shirou-AL** [comment]
On the upper left hand side next to the download and clone option, theres a tab saying "master". Click on that and select Blender 2.8, then download and install again.
